### PR TITLE
feat: upgrade to latest bs-platform and reason-react-native

### PR DESCRIPTION
**Pull request by baransu**
Not sure how to correctly use event functors as they are not "zero-cost" looking for a JS output. If you have suggestions on how to improve that, please let me know.
***
I found nor `yarn.lock` or `package-lock.json` was included or excluded so I added `yarn.lock` as I'm using `yarn` myself. If this is something you want to exclude I'll adjust the PR.

### CODE REVIEW

**Comment by sgny** [comment]
I hadn't been able to take the time to update these, and your contribution is *much* appreciated. I hope to be able to review this tonight - a first glance indicates all's fine.

I have until now preferred to exclude `yarn.lock`, but we can introduce that.

**Comment by baransu** [comment]
No pressure 🙂  Thanks!

**Comment by sgny** [comment]
An `include` statement instead of defining a new submodule eliminates some of the JS output due to the functors. However, that only would work when there is only one event type as with each include statement we'd get a new type `t` which would be worse than this result.

Defining interfaces would eliminate some of that superfluous output but I would expect it would make no difference in the final JS bundle for the React Native project.

Thanks once again, I'll publish a new npm package soon after.

**Comment by baransu** [comment]
@sgny Any progress on publishing to npm?

**Pull request merged**
